# Generated by Django 3.0.2 on 2020-04-22 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usernmae_name_principle', models.CharField(max_length=50)),
                ('password_principle', models.CharField(max_length=50)),
            ],
        ),
    ]
